import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { useAuth } from "../context/AuthContext";
import { acceptPlan } from "../services/userService";
import { generateWorkoutPlan, getProgress, getWorkoutPlan, toggleWorkoutComplete } from "../services/workoutService";
import { useToast } from "../context/ToastContext";

export default function Plan() {
  const { user, setUser } = useAuth();
  const navigate = useNavigate();
  const { toast } = useToast();
  const [openWeek, setOpenWeek] = useState(1);
  const [selected, setSelected] = useState(null);
  const [progress, setProgress] = useState(getProgress());
  const plan = getWorkoutPlan() || generateWorkoutPlan({
    goal: user.profile?.goal,
    weeks: 4,
  });

  async function finish() {
    setUser(await acceptPlan());
    navigate("/home");
  }

  if (!plan) {
    return (
      <div className="panel">
        <h1>No plan yet</h1>
        <p>Complete goal assessment to generate a starter plan.</p>
      </div>
    );
  }

  return (
    <div className="panel" style={{ maxWidth: 860 }}>
      <span className="eyebrow">YOUR PLAN</span>
      <h1>A 4-week starter plan</h1>
      <p className="disclaimer">This plan is a frontend template based on your goal. It is not generated by a live AI model yet.</p>
      {plan.weeks.map((week) => (
        <div className="week-block" key={week.week}>
          <button className="week-head" onClick={() => setOpenWeek(openWeek === week.week ? 0 : week.week)}>
            WEEK {week.week} <span>{openWeek === week.week ? "–" : "+"}</span>
          </button>
          {openWeek === week.week && week.days.map((day) => (
            <div className="day-row" key={day.id}>
              <strong>{day.day}</strong>
              <span>{day.title}{day.note ? ` · ${day.note}` : ""}</span>
              <span>{day.minutes ? `${day.minutes} min` : "Rest"}</span>
              <div className="btn-row">
                {day.exercises.length > 0 && (
                  <button className="link-btn" onClick={() => setSelected(day)}>View</button>
                )}
                <button
                  className="secondary-btn"
                  onClick={() => {
                    const next = toggleWorkoutComplete(day.id);
                    setProgress(next);
                    toast(next.workouts[day.id] ? "Workout marked complete" : "Marked incomplete");
                  }}
                >
                  {progress.workouts[day.id] ? "Done" : "Complete"}
                </button>
              </div>
            </div>
          ))}
        </div>
      ))}
      <button className="primary-btn" onClick={finish}>Go to my dashboard</button>

      {selected && (
        <div className="modal-backdrop" onClick={() => setSelected(null)}>
          <div className="modal" onClick={(e) => e.stopPropagation()}>
            <button className="close" onClick={() => setSelected(null)}>×</button>
            <h2>{selected.title}</h2>
            <p>{selected.day} · {selected.minutes} min</p>
            {selected.exercises.map((exercise) => (
              <div className="exercise" key={exercise.id}>
                <span>{exercise.name}</span>
                <b>{exercise.sets} × {exercise.reps}</b>
                <span>{exercise.rest}</span>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}
